# apiVersion: backstage.io/v1alpha1
# kind: Component
# metadata:
#   name: react-app1
#   annotations:
#     github.com/project-slug: imprem/react-app1
#     backstage.io/techdocs-ref: dir:.
# spec:
#   type: website
#   lifecycle: unknown
#   owner: guests
#   system: test-app
#   consumesApis: 
#     - 'component:weather-app' 
#     - 'component:tokenBalance-app'
#     - 'component:poductDetails-app'

apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: My-Backstage-Webside
  description: This is a dummy React app
  tags:
    - react
    - web
spec:
  type: website
  lifecycle: experimental
  owner: guests
  consumesApis:
    - api:weather-api
    - api:product-api
    - api:Tier1-token-api
    - api:Tier2-token-api
  dependsOn:
    - component:product-app
    - component:weather-app  
    - component:Token-Balance-App
